---
- hosts: all
  become: true
  tasks:
  - include_tasks: tasks/disable-swap.yml

  - name: Add /etc/modules-load.d/k8s-reqs.conf
    ansible.builtin.copy:
      dest: /etc/modules-load.d/k8s-reqs.conf
      content: |
        overlay
        br_netfilter

  - name: Add k8s.conf
    ansible.builtin.copy:
      dest: /etc/sysctl.d/98-k8s-reqs.conf
      content: |
        net.bridge.bridge-nf-call-iptables = 1
        net.bridge.bridge-nf-call-ip6tables = 1
        net.ipv4.ip_forward = 1
        vm.swappiness = 0

  - name: Stop and disable ufw.service
    ansible.builtin.systemd:
      name: ufw.service
      state: stopped
      enabled: false

  - name: Reboot
    ansible.builtin.reboot:
