---
- hosts: kube-node-0
  become: true
  tasks:
  - name: Initialize the Kubernetes cluster using kubeadm
    ansible.builtin.command: |
      kubeadm init --apiserver-advertise-address="{{ hostvars[inventory_hostname]['ansible_ssh_host'] }}" \
                   --apiserver-cert-extra-sans="kube.cluster.local,{{ hostvars[inventory_hostname]['ansible_ssh_host'] }}"   \
                   --node-name {{ inventory_hostname }} \
                   --pod-network-cidr=10.42.0.0/16
    args:
      creates: /etc/kubernetes/pki/etcd/server.key
    register: kubeadm_init_control

  - name: Print return information from the previous task
    ansible.builtin.debug:
      var: kubeadm_init_control
      verbosity: 0

  - name: Setup kube config for ubuntu user
    ansible.builtin.command: "{{ item }}"
    with_items:
      - mkdir -p /home/ubuntu/.kube
      - cp -f /etc/kubernetes/admin.conf /home/ubuntu/.kube/config
      - chown ubuntu:ubuntu /home/ubuntu/.kube
      - chown ubuntu:ubuntu /home/ubuntu/.kube/config
    args:
      creates: /home/ubuntu/.kube/config

  # # https://kubernetes.io/docs/concepts/cluster-administration/addons/#networking-and-network-policy
  # # https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm/#pod-network

  # # CALICO
  # # https://projectcalico.docs.tigera.io/getting-started/kubernetes/self-managed-onprem/onpremises
  # # https://projectcalico.docs.tigera.io/getting-started/kubernetes/self-managed-onprem/onpremises#install-calico-with-kubernetes-api-datastore-50-nodes-or-less
  - name: Install calico pod network
    become: false
    ansible.builtin.command: sudo kubectl --kubeconfig=/home/ubuntu/.kube/config apply -f https://raw.githubusercontent.com/projectcalico/calico/v3.24.5/manifests/calico.yaml    args:
      creates: /opt/cni/bin/calico


  - name: Generate join command
    ansible.builtin.command: kubeadm token create --print-join-command
    register: join_command


- hosts: nodes
  become: true
  tasks:
  - name: Run a command to join cluster
    ansible.builtin.shell: "{{ hostvars['kube-node-0']['join_command'].stdout_lines | first }}"
    args:
      creates: /opt/cni/bin/calico
