---
- hosts: manager
  become: true
  tasks:
  - name: Initialize the Kubernetes cluster using kubeadm
    command: |
      kubeadm init --apiserver-advertise-address="{{ hostvars[inventory_hostname]['ansible_ssh_host'] }}" \
                   --apiserver-cert-extra-sans="kube.cluster.local,{{ hostvars[inventory_hostname]['ansible_ssh_host'] }}"   \
                   --node-name manager \
                   --pod-network-cidr=10.88.0.0/16

  - name: Setup kubeconfig for vagrant user
    command: "{{ item }}"
    with_items:
     - mkdir -p /home/vagrant/.kube
     - cp -i /etc/kubernetes/admin.conf /home/vagrant/.kube/config
     - chown vagrant:vagrant /home/vagrant/.kube/config

  #https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm/#pod-network
  - name: Install calico pod network
    become: false
    command: kubectl apply -f https://docs.projectcalico.org/manifests/calico.yaml

  - name: Generate join command
    command: kubeadm token create --print-join-command
    register: join_command

  handlers:
    - name: docker status
      service: name=docker state=started

- hosts: nodes
  become: true
  tasks:
  - name: Run a command to join cluster
    shell: "{{ hostvars['manager']['join_command'].stdout_lines | first }}"
  handlers:
    - name: docker status
      service: name=docker state=started
